devfile/registry-operator

- .ci/openshift_integration.sh
- tests/integration/pkg/deploy/controller.go
- Prints the output of the command that installs the regisry CRDs
- Ensures kustomize and controller-gen are installed before running tests
Signed-off-by: John Collier <jcollier@redhat.com>
> Add debug statements to tests

- Makefile
- tests/integration/pkg/client/oc.go
- tests/integration/pkg/tests/devfileregistry_tests.go
The OpenShift CI doesn't have Kubectl installed, so updating the integration tests to use `oc` instead of `kubectl`.
> Use oc in integration tests

- .ci/openshift_integration.sh
Updates the OpenShift CI test scripts for this repo so that the operator image built by the CI is used, rather than the one hosted on quay.io
@devfile/qe-team
> Update CI test script to use built operator image

- README.md
- controllers/update.go
- pkg/registry/defaults.go
- pkg/registry/service.go
- samples/registry-k8s.yaml
- samples/registry-no-storage.yaml
- samples/registry.yaml
- tests/integration/pkg/tests/devfileregistry_tests.go
- Update readme to add section on deploying the registry on both Kubernetes and OpenShift
- Make sure the index server's metrics port is enabled in the Kubernetes Service
- Make sure the default image for the devfile index image is set
- Updates test to check that both the index and oci metrics servers are running, and not just the oci one
> Miscellaneous improvements to the registry operator

- README.md
- api/v1alpha1/devfileregistry_types.go
- config/crd/bases/registry.devfile.io_devfileregistries.yaml
- pkg/registry/defaults.go
- pkg/registry/deployment.go
This PR adds the telemetry option to consumer so that consumer can opt in/out the registry telemetry when using operator to deploy the registry.
Signed-off-by: Jingfu Wang <jingfwan@redhat.com>
> Add telemetry option

- controllers/ensure.go
- pkg/registry/configmap.go
- pkg/registry/deployment.go
- pkg/registry/naming.go
- tests/integration/pkg/tests/devfileregistry_tests.go
Updates the registry operator to support the devfile registry viewer:
- Adds the viewer config json file to the registry config map
- Adds a startupProbe
> Update the operator to support the registry viewer

- controllers/update.go
Signed-off-by: Kim Tsao <ktsao@redhat.com>
Fixes PR: https://github.com/devfile/api/issues/784
Manual Testing:
- Deployed new operator to CRC
- Deployed Devfile registry and updated/deleted a combination of single and multiple properties
Verified pods were automatically re-created with new ENV variable values
> Add telemetry configs for updating

- Makefile
- config/crd/bases/registry.devfile.io_devfileregistries.yaml
- pkg/registry/configmap.go
- pkg/registry/defaults.go
- pkg/registry/deployment.go
operator bugfix
Bugfix changes include:
- Removes unnecessary escape characters used on [pkg/registry/configmap.go#L55](https://github.com/devfile/registry-operator/blob/71b9284a12630989184a8cf926a97543ef8da65f/pkg/registry/configmap.go#L55) which cause the registry viewer to fail the JSON parsing process and fail to deploy. 
- Changes for devfile/api#1016 applied.
- Changes for devfile/api#1019 applied.
- Adds container security contexts required by OCP 4.12.
- Add pod security contexts if storage is enabled.
- Makefile now lets user override the `K8S_CLI` variable.
- Missing `registryViewerWriteKey` added to the devfile registries crd config.
Fixes #?
fixes …
> Deployment bugfixes

- .github/workflows/ci.yaml
- Makefile
Signed-off-by: Michael Valdron <mvaldron@redhat.com>
CI
Applies latest version which does not require golang 1.19, so that this CI check does not break during module install.
Fixes #?
part of devfile/api#1021
Documentation
> Use gosec v2.14.0 to prevent breakage

- api/v1alpha1/devfileregistry_types.go
- bundle/manifests/registry.devfile.io_devfileregistries.yaml
- config/crd/bases/registry.devfile.io_devfileregistries.yaml
- pkg/registry/defaults.go
- pkg/registry/defaults_test.go
- pkg/registry/deployment.go
Storage enabled volume property now defaults to false, OCI registry volume now uses `emptydir` by default. This change fixes permission issues for kubernetes deployments and is work towards proper OCP 4.12 support.
Fixes #?
fixes devfile/api#1029
part of devfile/api#1092
Documentation
**How to test changes / Special notes to the …
> Storage enabled volume defaults to false

- api/v1alpha1/clusterdevfileregistrieslist_webhook.go
- api/v1alpha1/clusterdevfileregistrieslist_webhook_test.go
- api/v1alpha1/devfileregistrieslist_webhook.go
- api/v1alpha1/devfileregistrieslist_webhook_test.go
- api/v1alpha1/devfileregistry_webhook.go
- api/v1alpha1/devfileregistry_webhook_test.go
- api/v1alpha1/validate.go
- api/v1alpha1/validate_test.go
- api/v1alpha1/webhook_suite_test.go
- bundle/manifests/registry-operator.clusterserviceversion.yaml
- config/webhook/manifests.yaml
- main.go
Adds namespace validation to webhooks for `devfileregistry`, `devfileregistries`, and `clusterdevfileregistrieslist` to prevent deployment to the default namespace.
Fixes #?
part of devfile/api#1092
Documentation
> Add namespace webhook validation

- CLUSTER_SUPPORT.md
- Makefile
- README.md
registry operator documentation
This PR adds an outline of requirements for deployments made by the registry operator. This ensures users who wish to use the registry operator to make deployments know what target cluster environments are supported and to avoid default namespaces.
Fixes #?
fixes devfile/api#662
Documentation
**How to test changes / …
> Outline deployment requirements

- CONTRIBUTING.md
- DEVFILE_REGISTRY.md
- README.md
- REGISTRIES_LISTS.md
- api/v1alpha1/devfileregistry_types.go
- bundle/manifests/registry.devfile.io_devfileregistries.yaml
- config/crd/bases/registry.devfile.io_devfileregistries.yaml
Fixes https://github.com/devfile/api/issues/1015
Fixes partially https://github.com/devfile/api/issues/1233
Documentation
> Complete documentation coverage of registry operator

- license_header.txt
Updates license header file to have the `Copyright Red Hat` format instead of `Copyright [year] Red Hat, Inc.`.
Fixes #?
fixes devfile/api#1243
- Are all your changes documented under the [upcoming release](https://github.com/devfile/registry-operator/tree/main/CHANGELOG.md#unreleased) entry?
Documentation
**How to test changes / Special notes to …
> [Devtools week] Update license headers

- README.md
- tests/integration/pkg/client/client.go
- tests/integration/pkg/client/oc.go
- tests/integration/pkg/tests/devfileregistry_tests.go
Fixes https://github.com/devfile/api/issues/1239
Documentation
- Run make test-integration with oc only, kubectl only, none of them present in the PATH.
- Define K8S_CLI with the preferred cli to use
> Detect and use oc / kubectl for integration tests

- .ci/openshift_integration.sh
- .codecov.yaml
- .github/workflows/ci.yaml
- .github/workflows/codecov.yaml
- .github/workflows/dockerimage-push.yaml
- Dockerfile
- Makefile
- add_licenses.sh
- bundle.Dockerfile
- registry.yaml
- samples/clusterregistrieslist.yaml
- samples/devfileregistrieslist.yaml
- samples/registry-k8s.yaml
- samples/registry-no-storage.yaml
- samples/registry.yaml
Adds missing license headers to scripts, dockerfiles, workflows, and config files.
Related to: https://github.com/devfile/api/issues/1243
Fixes #?
Documentation
> Add license headers to scripts and configs

- Makefile
Fixes incorrect source paths for local build rules:
- [Makefile#L121](https://github.com/devfile/registry-operator/blob/b13d6d8c19a2c7af0f5e250e912c95a7bbc643ae/Makefile#L121)
- [Makefile#L125](https://github.com/devfile/registry-operator/blob/b13d6d8c19a2c7af0f5e250e912c95a7bbc643ae/Makefile#L125)
Fixes #?
fixes devfile/api#1329 …
> Correct source path for local build rules

- .github/workflows/dockerimage-push.yaml
- .github/workflows/release-pr.yaml
- .github/workflows/release.yaml
- check_version.sh
These changes are part of revisions to #56 changes to merge release changes to a release branch _before_ creating the release: https://github.com/devfile/api/issues/1267#issuecomment-1792837116
In addition, one of these changes reverts `docker/build-push-action` to `v1.1.2` the latest `v1.1.x` version which fixes the silent failures when pushing container images (devfile/api#1328).
Fixes #?
fixes part of devfile/api#1267
fixes devfile/api#1328
- Fix all MEDIUM and higher findings and/or annotate a finding per …
> Release branching workflow revisions

- CONTRIBUTING.md
- Makefile
- README.md
Registry-Operator
Implements podman script support for the Registry-Operator build and push commands
Fixes #?
https://github.com/devfile/api/issues/1340
Documentation
Run the new commands via CLI to build and push images created with podman instead of docker
> Implement Podman scripts for Registry-Operator Makefile

- CONTRIBUTING.md
- Dockerfile
- Makefile
- README.md
Adds support for building the registry operator binaries and container images to target other platforms and fixes missing pieces to properly run `make docker-buildx`.
**Additional changes**
- Updated environment variable table under `README.md`
- Includes build arg in `podman-build` make rule for enabling http/2 for webhook server
- Corrects `make docker-build` to `make <engine>-build` under instructions on enabling http/2 for webhook server
Fixes #?
fixes devfile/api#1383
- Fix all MEDIUM and higher findings and/or annotate a …
> [Devtools Week] Multi-platform support for build binary and container images

- README.md
documentation
Adds information about the releases and release cycle of the registry operator based on the complete release documentation under the [release process document](https://docs.google.com/document/d/1olp6CwhHUMqGmaXXMLRn3z_S34Da4mdkLfm3k8DH-SM/edit).
Fixes #?
fixes devfile/api#1194
Documentation
**How to test changes / Special notes to …
> Add releases section to README

- .github/workflows/scorecard.yml
- README.md
This is for the CNCF Cleaner badge as part of our effort to increase adherence to open source best practices.
This PR implements the GitHub workflow for code scanning for the OpenSSF scorecard. This tracks security vulnerabilities in the repository and gives the repo a score based off its findings. A similar issue to this was merged here: https://github.com/devfile/library/pull/195
fixes https://github.com/devfile/api/issues/1386 
- Fix all MEDIUM and higher findings and/or annotate a finding per gosec instructions: …
> add scorecard workflow and badge

- DEVFILE_REGISTRY.md
- README.md
This PR expands on our documentation relating to deploying a devfile registry to a cluster. There is currently an issue where the steps required to access a deployed registry differ based on OS. This fix adds special troubleshooting steps for those users on MacOS.
Fixes https://github.com/devfile/api/issues/1448
Documentation
**How to test changes …
> Add Documentation For Minikube and MacOS Deployment

- api/v1alpha1/devfileregistry_types.go
- config/crd/bases/registry.devfile.io_devfileregistries.yaml
- pkg/registry/defaults.go
- pkg/registry/defaults_test.go
This PR adds support for the CRD field of the ingress class in the `registry-operator`.
fixes https://github.com/devfile/api/issues/1434
Fixes #?
Documentation
> Add ingressClass CRD field

- README.md
- pkg/registry/ingress.go
- pkg/registry/ingress_test.go
This PR updates the operator hostname to be consistent in its definition between the Helm deployment and the openshift deployment. Prior to this change the Helm chart implemented the CR name coupled with the namespace to create the hostname whereas the openshift deployment only used the CR name and the ingress.
Additionally the readme was updated with a `Known Issues` section as during testing I was trying to run `make test-integration` on Minikube, however, it was timing out and I could not figure out why this was happening. There was an active issue that outlined this and it would be good for others to be aware of known issues such as this in the future.
Some unit tests were also added to verify that …
> Update Ingress and Hostname

- api/v1alpha1/devfileregistry_types.go
- config/crd/bases/registry.devfile.io_devfileregistries.yaml
- pkg/registry/defaults.go
- pkg/registry/defaults_test.go
operator api
Adds override fields from the helm chart to the `DevfileRegistry` CRD:
- `hostnameOverride`
- `nameOverride`
- `fullnameOverride`
Fixes #?
fixes devfile/api#1439
Documentation
> Add override CRD fields

- Makefile
operator 
test
Fixes `sigs.k8s.io/controller-runtime/tools/setup-envtest` to revision `v0.0.0-20240405143037-c25fe2f5ca0f` to workaround https://github.com/kubernetes-sigs/controller-runtime/issues/2744.
Fixes #?
fixes devfile/api#1519
Documentation
> Fix `setup-envtest` version

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Documentation updates
This PR updates the documentation for how to properly test the Devfile Registry Operator. This also updates the PR template to include these instructions so reviewers will always have that information readily available.
No issue
Documentation
> Update Testing Documentation

- .github/workflows/ci.yaml
- .github/workflows/dockerimage-push.yaml
- Makefile
- README.md
CI and multi-arch building
This PR enables the images built for the registry-operator to be multi-arch. Previously there was a `make` command `make docker-buildx` that built and pushed multi-arch images but it was not included in any of our CI. This PR updates that command to incorporate it into our CI alongside a new command, `make docker-bundle-buildx` to allow the bundle to also be built for multiple architectures. 
Since `buildx` is a docker command I also created a `make podman-buildx` command, this is a clone of `make docker-buildx` but redesigned to work with podman and its specific commands.
Both `ci.yaml` and `dockerimage-push.yaml` were updated to now reference the `buildx` commands for …
> Multi Arch Support for Registry Operator

- go.mod
- go.sum
This PR bumps the `registry-support` dependencies as they received a critical security fix.
Part of https://github.com/devfile/api/issues/1620
Documentation
**Testing changes**
[Running Unit Tests](https://github.com/devfile/registry-operator/blob/main/CONTRIBUTING.md#unit-tests)
[Running Integration …
> Bump registry-support dependencies

- Makefile
- README.md
cert-manager version v1.11.0---> v1.13.1 (latest version)
Fixes # https://github.com/devfile/api/issues/1320
- [✅  ] Test Coverage 
Documentation
**Testing changes**
```
kubectl get pods -n cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-67f7b4f67d-jc9dx              1/1     Running   0 …
```
> Updated cert-manager version v1.11.0---> v1.15.1   

- .github/workflows/ci.yaml
- Makefile
- README.md
- bundle/manifests/registry.devfile.io_clusterdevfileregistrieslists.yaml
- bundle/manifests/registry.devfile.io_devfileregistries.yaml
- bundle/manifests/registry.devfile.io_devfileregistrieslists.yaml
- config/crd/bases/registry.devfile.io_clusterdevfileregistrieslists.yaml
- config/crd/bases/registry.devfile.io_devfileregistries.yaml
- config/crd/bases/registry.devfile.io_devfileregistrieslists.yaml
_Summarize the changes you made as part of this PR._
This PR removes the `-u` flag from our `go get` statements and also changes the pins from sha to a version to make it easier to identify what we are running on. Both of these versions have `go.mod` files that only contain dependencies for go 1.21 or earlier so we won't encounter the issue of requiring go 1.22+ anymore. 
Since we are not always going to be on the latest Go version (historically have been lagging behind by a version or two) it is best to remove the `-u` flag to ensure we don't encounter this issue again where some dependency outpaces our Go version.
_Link the GitHub/GitLab/JIRA issues that are related to this PR._
resolves https://github.com/devfile/api/issues/1643
- Are your changes sufficiently tested, and are any …
> pin dependencies to versions for go 1.21 and remove update flag

- .github/workflows/ci.yaml
- Dockerfile
- Makefile
- README.md
- go.mod
Bumps Go version to 1.22 to patch runtime and support upcoming compatibility changes.
resolves https://github.com/devfile/api/issues/1694
_Explain what tests you personally ran to ensure the changes are functioning as expected._
_Instructions for the reviewer on how to test your changes._
[Running Unit Tests](https://github.com/devfile/registry-operator/blob/main/CONTRIBUTING.md#unit-tests)
[Running Integration Tests](https://github.com/devfile/registry-operator/blob/main/CONTRIBUTING.md#integra …
> Update to Go 1.22
